FROM gettyimages/spark:2.1.1-hadoop-2.7
MAINTAINER Christoph Schranz <christoph.schranz@salzburgresearch.at>

# Install Anaconda SciPy Stack
RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \ 
    git mercurial subversion 

ENV CONTREPO https://repo.continuum.io/archive/
ENV ANACONDAURL $(wget -q -O - $CONTREPO index.html | grep "Anaconda3-" | grep "Linux" | grep "86_64" | head -n 1 | cut -d \" -f 2)

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh

 
RUN wget --quiet https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -O ~/anaconda.sh

RUN /bin/bash ~/anaconda.sh -b -p /opt/conda

RUN rm ~/anaconda.sh

RUN apt-get install -y curl grep sed dpkg && \ 
    TINI_VERSION=`curl https://github.com/krallin/tini/releases/latest | grep -o "/v.*\"" | sed 's:^..\(.*\).$:\1:'` && \ 
    curl -L "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" > tini.deb && \ 
    dpkg -i tini.deb && \ 
    rm tini.deb && \ 
    apt-get clean 

ENV PATH /opt/conda/bin:$PATH 

ENTRYPOINT [ "/usr/bin/tini", "--" ] 
CMD [ "/bin/bash" ]


